[package]
name = "voicevox_core_wasm"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "wasm_browser_api_smoke"
path = "src/main.rs"

[dependencies]
voicevox_core = { workspace = true, features = ["link-onnxruntime", "wasm-open-jtalk-link-smoke"] }
