[package]
name = "voicevox_core_wasm"
version.workspace = true
edition.workspace = true
publish = false
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "wasm_c_api_binding_smoke"
path = "src/main.rs"

[dependencies]
voicevox_core_c_api = { package = "voicevox_core_c_api", path = "../voicevox_core_c_api", features = ["link-onnxruntime", "wasm-open-jtalk-link-smoke"] }
